on: [push]

jobs:
  build-node:
    runs-on: ubuntu-latest
    name: Sync commits to Notion
    steps:
      - name: Sync Github Commit to Notion
        id: notion-sync-commit
        uses: marlisumarli/sync-github-to-notion@1.0.2
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          notion_database: ${{ secrets.NOTION_DATABASE }}
          branch: ${{ github.ref_name }}
